import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/About.module.css'
import data from '../data/employees.json'
import { useState } from 'react'
import Employee from '../components/employees'
import Header from '../components/header'
import Footer from '../components/footer'


const inter = Inter({ subsets: ['latin'] })

export default function About() {

  console.log(data);

  const [information, setInformation] = useState([...data])

  return (
      <>
        <Head>
          <title>CRIT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,900;1,800&family=Roboto:wght@500&display=swap" rel="stylesheet"></link>
        </Head>
        <main className={styles.about}>
            <Header />
            {
            information && information.map((info, index) => {
                if (info.lastName.toLowerCase() === "rutt") {
                    return(
                        <Employee 
                            key={index} 
                            firstName={info.firstName} 
                            lastName={info.lastName}
                            position={info.position} 
                            bio={info.bio}
                            className="employee_card" 
                        />
                    )
                }
            })
            }
            {
                information && information.map((info, index) => {
                    if (info.lastName.toLowerCase() === "hammer") {
                        return(
                            <Employee 
                                key={index} 
                                firstName={info.firstName} 
                                lastName={info.lastName}
                                position={info.position}
                                bio={info.bio}   
                                className="employee_card" 
                            />
                        )
                    }
            })
            }
            {
                information && information.map((info, index) => {
                    if (info.lastName.toLowerCase() === "ice") {
                    return(
                        <Employee 
                            key={index} 
                            firstName={info.firstName} 
                            lastName={info.lastName}
                            position={info.position}  
                            bio={info.bio}   
                            className="employee_card" 
                        />
                    )
                    }
                })
            }
            <Footer />
        </main>
      </>
    )
  }
