import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/cards'
import Header from '../components/header'
import Footer from '../components/footer'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data);

  const [information, setInformation] = useState([...data])

  return (
      <>
        <Head>
          <title>CRIT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,900;1,800&family=Roboto:wght@500&display=swap" rel="stylesheet"></link>
        </Head>
        <main className={styles.main}>
          <Header />
          {
            information && information.map((info, index) => {
              if (info.department.toLowerCase() === "business") {
                return(
                  <Card key={index} degree={info.degree} description={info.description} department={info.department} className="business_card" />
                )
              }
            })
          }
          {
            information && information.map((info, index) => {
              if (info.department.toLowerCase() === "computing") {
                return(
                  <Card key={index} degree={info.degree} description={info.description} department={info.department} className="business_card" />
                )
              }
            })
          }
          <Footer />
        </main>
      </>
    )
  }
